### ISSUE TITLE
Integration with Dingo

### ISSUE THREAD

**Issue by pedrommone** [jedrzej/withable#4]
How can we integrate it woth Fractral Transformers? I'm working with Dingo for response API requests.

**Comment by jedrzej** [comment]
Hey,
I haven't used fracta/dingo. I had a look at http://fractal.thephpleague.com/transformers/ though - I believe those are the transformers that you mean. As far as I can see they are used to transform the response - they get passed some result set and transform the output. "withable" behaviour is applied when data is loaded from the database, not when generating response, therefore I don't really see a need for integration.

See the first example transformer - data is loaded with 

$books = Book::all();

If Book model uses Withable trait, "with" parameter from the request will be applied automatically.

**Comment by jedrzej** [comment]
Ah, I think I know what you meant - do you want the "with" parameter to automatically add selected relations to the response? If so, I don't think it's possible as response structure is fully customizable. Automatically inserting relations into such custom response would require inserting them in a fixed place in the response, which would reduce ability to customize the response.

**Comment by pedrommone** [comment]
But, we cannot pass it on http request? Like `books?include=stores,authors,comments`

**Comment by jedrzej** [comment]
First of all, the list of relations to eagerly load should be an array, so the URL should be:

    books?include[]=stores&include[]=authors&include[]=comments

You should also customize the name of the parameter that passes the list of relations to load:

    protected $withParameterName = 'include';

Then it should work - with the following call relations should be eagerly loaded:

    $books = Book::withRelations()->get();

**Comment by pedrommone** [comment]
Ok, it sounds great, but.. When I try to eadge loading on ´League/Transformers´, if I dont include the `ìnclude` on default value, it doesnt load when I ask for ´books?include[]=stores&include[]=authors&include[]=comments´

**Comment by jedrzej** [comment]
Could you paste your transformer? You need to explicitely tell in the transformer where you want those relations to be stored.
